services:
  - type: web
    name: narrato-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://narrato-backend.onrender.com
