services:
  # Backend Service
  - type: web
    name: narrato-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    region: oregon
    plan: starter

  # Frontend Service
  - type: web
    name: narrato-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://narrato-backend.onrender.com
    region: oregon
    plan: starter
